CREATE TABLE ta_owner (id VARCHAR(64) PRIMARY KEY, created_at TIMESTAMP WITH TIME ZONE NOT NULL);
CREATE TABLE ta_conversation (
 id VARCHAR(36) PRIMARY KEY, owner_id VARCHAR(64) NOT NULL REFERENCES ta_owner(id),
 title VARCHAR(120) NOT NULL, mode VARCHAR(12) NOT NULL CHECK(mode IN ('CHAT','AGENT')),
 constraints_text TEXT NOT NULL DEFAULT '', created_at TIMESTAMP WITH TIME ZONE NOT NULL,
 updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX ta_conversation_owner ON ta_conversation(owner_id, updated_at);
CREATE TABLE ta_run (
 id VARCHAR(36) PRIMARY KEY, conversation_id VARCHAR(36) NOT NULL REFERENCES ta_conversation(id),
 request_key VARCHAR(80) NOT NULL, request_text TEXT NOT NULL, constraints_text TEXT NOT NULL,
 status VARCHAR(20) NOT NULL, error_code VARCHAR(64), model VARCHAR(100) NOT NULL,
 prompt_version VARCHAR(64) NOT NULL, knowledge_version VARCHAR(100) NOT NULL,
 tool_policy TEXT NOT NULL, next_event BIGINT NOT NULL DEFAULT 0,
 created_at TIMESTAMP WITH TIME ZONE NOT NULL, finished_at TIMESTAMP WITH TIME ZONE,
 UNIQUE(conversation_id, request_key)
);
CREATE INDEX ta_run_conversation ON ta_run(conversation_id, created_at);
CREATE INDEX ta_run_status ON ta_run(status);
CREATE TABLE ta_message (
 seq BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 conversation_id VARCHAR(36) NOT NULL REFERENCES ta_conversation(id),
 run_id VARCHAR(36) NOT NULL REFERENCES ta_run(id), role VARCHAR(12) NOT NULL,
 content TEXT NOT NULL, status VARCHAR(20) NOT NULL,
 created_at TIMESTAMP WITH TIME ZONE NOT NULL, UNIQUE(run_id, role)
);
CREATE INDEX ta_message_conversation ON ta_message(conversation_id, seq);
CREATE TABLE ta_run_event (
 run_id VARCHAR(36) NOT NULL REFERENCES ta_run(id), seq BIGINT NOT NULL,
 type VARCHAR(20) NOT NULL, payload TEXT NOT NULL, created_at TIMESTAMP WITH TIME ZONE NOT NULL,
 PRIMARY KEY(run_id, seq)
);
CREATE TABLE ta_model_call (
 id VARCHAR(36) PRIMARY KEY, run_id VARCHAR(36) NOT NULL REFERENCES ta_run(id),
 purpose VARCHAR(30) NOT NULL, input_tokens INT NOT NULL, output_tokens INT NOT NULL,
 estimated BOOLEAN NOT NULL, status VARCHAR(20) NOT NULL, latency_ms BIGINT NOT NULL,
 first_token_ms BIGINT, created_at TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX ta_call_run ON ta_model_call(run_id);
CREATE TABLE ta_tool_execution (
 id VARCHAR(36) PRIMARY KEY, run_id VARCHAR(36) NOT NULL REFERENCES ta_run(id),
 tool_name VARCHAR(200) NOT NULL, status VARCHAR(20) NOT NULL, latency_ms BIGINT NOT NULL,
 created_at TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE TABLE ta_summary (
 conversation_id VARCHAR(36) PRIMARY KEY REFERENCES ta_conversation(id),
 version INT NOT NULL, covered_seq BIGINT NOT NULL, content TEXT NOT NULL,
 updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);
